apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
        app: frontend
  name: frontend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: edilson35s78/frontend
        name: frontend
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
