apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
        app: backend
  name: backend
  namespace: project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: wjosuep13/sa
        name: backend
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
